// data.js
const dbPlayers = [
  { nome: "nell", steamId: "111", lvl: 10, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "calvao", steamId: "222", lvl: 9, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "fankes", steamId: "333", lvl: 10, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "vit1nxd", steamId: "444", lvl: 9, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "Lucão", steamId: "555", lvl: 3, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "arthurzin", steamId: "666", lvl: 9, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "TRAVAA", steamId: "777", lvl: 6, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "Lincoln", steamId: "888", lvl: 5, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "Dini", steamId: "999", lvl: 6, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "Lincão", steamId: "101", lvl: 5, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "Rocha", steamId: "101", lvl: 7, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "Toinho", steamId: "101", lvl: 7, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "Th", steamId: "101", lvl: 6, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "ep1c", steamId: "101", lvl: 5, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "konfuzed", steamId: "101", lvl: 7, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "ezk", steamId: "101", lvl: 8, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "k0ber", steamId: "101", lvl: 8, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "Liniker", steamId: "101", lvl: 7, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "sprayking", steamId: "101", lvl: 4, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "MAYCAO", steamId: "101", lvl: 7, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "VINAO", steamId: "101", lvl: 10, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
  { nome: "lu1sz-", steamId: "101", lvl: 8, partidas: 0, vitorias: 0, derrotas: 0, kills: 0, deaths: 0, sumRating: 0 },
];